/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fernandopaniagua.gwvg.ui;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paniagua
 */
public class JFMain extends javax.swing.JFrame {

    private int XPos;//JFrame x position
    private int YPos;//JFrame y position
    public static final int SCREEN_WIDTH = 1000;
    public static final int SCREEN_HEIGHT = 600;

    JPScreenTest jpst = new JPScreenTest();

    /**
     * Creates new form JFSW
     */
    public JFMain() {
        initComponents();
        this.setTitle(("Galactic War Vector Game - By Fernando Paniagua"));
        //Calcular dimensiones de la pantalla
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        XPos = (gd.getDisplayMode().getWidth()-SCREEN_WIDTH)/2;
        YPos = (gd.getDisplayMode().getHeight()-SCREEN_HEIGHT)/2;
        //Los parámetros de los insets corrigen espacios de bordes, toolbar, etc.
        this.setBounds(this.XPos, this.YPos,
                JFMain.SCREEN_WIDTH + this.getInsets().left + this.getInsets().right,
                JFMain.SCREEN_HEIGHT + jmbBarraMenu.getHeight() + this.getInsets().bottom + this.getInsets().top);
        this.getContentPane().add("test", jpst);
        new Thread() {
            public void run() {
                while (true) {
                    jpst.repaint();
                    try {
                        sleep(7);
                        //sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }

    private void finishProgram() {
        //TODO Actions before finish program

        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jmiAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenuFile.setText("File");

        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jmiExit);

        jmbBarraMenu.add(jMenuFile);

        jMenuHelp.setText("Help");

        jmiAbout.setText("About");
        jMenuHelp.add(jmiAbout);

        jmbBarraMenu.add(jMenuHelp);

        setJMenuBar(jmbBarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        finishProgram();
    }//GEN-LAST:event_jmiExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiAbout;
    private javax.swing.JMenuItem jmiExit;
    // End of variables declaration//GEN-END:variables
}
